---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age1hwuafwcf6l05rd0erpl99wlrt5m644n5sxr5n0t70v93zj62humqh4j3ln
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1hwuafwcf6l05rd0erpl99wlrt5m644n5sxr5n0t70v93zj62humqh4j3ln
