# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Naih2zh1Y/0d3GJBxQ==,iv:ttevtcPlM56f8FTmUZLapkxc7RcmdWV6zFvR/KAD8Lk=,tag:+DLY1gRTA8m/dmkYR+Cvqg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:oy7oieN9CXzOZYOon3PUmgFx+nxDlBc2+5pLMcV+s/zFUb07oQ==,iv:fIdPZmB3SCcVKP1aE0MmEQrHAFkc9RDyEOQcsa6u41I=,tag:3ClXNOydmZinpO6Igr7fNQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:oeBkt5wonnVN2f1DjA==,iv:hyBAq6QETmCTTDxh+HnuayUdy1eVd2SQVJ6z0266ceI=,tag:X0zgAEg+bJb3hxDvgymciw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hwuafwcf6l05rd0erpl99wlrt5m644n5sxr5n0t70v93zj62humqh4j3ln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWlJTSHg1UmNoU0tUam40
            UXV0TWtpeHdPR1JJTlhGSVUyMmZtSzBaRTBRClVJR3BVc3hoK0MrN0pkNDRDQ2d3
            SXV3NVphWDFpTGZJd3hVRUFobWlhbEUKLS0tIDRhd3p4bUl3L1R6c1ZkQVQ2ZXVt
            QmorL0dFekMvSHJuNDZGTUxPMktOU1kK79khRE/Q51gxfp871nBoV3oWyQnAGaB3
            TVIeCBfX/respT3iAMUctkLZ43yJvEx5rJblO4XOcWp5VtMsBAxnMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-16T17:14:04Z"
    mac: ENC[AES256_GCM,data:aPXCX4ysetR2uM9D8sG6gAjMQwHN9PxrLT0vCO7VmQD3XafNdWzWbrrYfmeDiv4b96mPWsgqOhl8UUa3KzV8DiSQVs6ssZn6QKIzul5IkoSHHPguU/Lb1cj2oV5+YAySJEIn5jfDHgM9k8Sh6MyzxJkxGQdRuSsHP0lAgexLa20=,iv:A8D7f8A6re+mfsWFEXvEhcjA6r3YA0hq83uQQIDUOLg=,tag:8RPBmg4qfVwtVyuQegKXUg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
