# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:8g/YXZavxP4HS1X4zg==,iv:FELHyToXKshdXFWuR3jDZHnc/MiwmtaQL4gFhm6SFmY=,tag:wXt0NJvPTqEGaO9VFQK1qw==,type:str]
    api-key: ENC[AES256_GCM,data:lsS0JNuaoO3LZ4V20F2ZQ+g+pfXw1qgBOWpB0jGpBh5XBtJr8w==,iv:EcjpoBtq4UutUcqipyEaNxebLPj2W+/q1aMVzvxSmOw=,tag:zWIJKbjMQ0l3ZF3+uqR48Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hwuafwcf6l05rd0erpl99wlrt5m644n5sxr5n0t70v93zj62humqh4j3ln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWXYyYkRGMExRTVJPUGtB
            WW1tYUVwRko5VmpNOURSZmZKb0UrL0sxTmp3CmpQZGJ2OFBiN0F6Q1phOGsxY055
            dkhBZTBmT0Nxb2pHbVFIWG1pa0htbDgKLS0tIExnSTlJSThhUENlR1F2SVc0VW1N
            Zll3dXdnc3lCOC90akxMTWNMc0hHTmcK1GwLny1EDEWRF2LLFgoxe4EywV9Mstd2
            pbdYsNxzHIlZDYU9HTkIelO5yOlVl+8da5dsqUP6XU7C/pDrF09rng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-16T17:14:04Z"
    mac: ENC[AES256_GCM,data:4gqsNFwGU4DXGA/0DjhXLhgq3MnH0xigx4xojIugaGpD5jtg/aw6AGfdv68suwPdSxgHyhfzVXYQzSSgdjWnELzgIABirVQV5/TWeuqiCoFnwfw5JS99urzZ2fTzdxmjXK1gg+UpxUDY/RviDcCiu0wVWT4G5bG6mrYZP9wbbo8=,iv:MkAe0c0Wbne7vig6+7o7el2PgvlkCHjV4IlklrC3ETY=,tag:BhM1gvgKWkWWGckTPpcLNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
