---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Etc/UTC
  METALLB_LB_RANGE: 10.10.10.200-10.10.10.240
  METALLB_K8S_GATEWAY_ADDR: 10.10.10.200
  METALLB_INGRESS_ADDR: 10.10.10.201
  SVC_PIHOLE_ADDR: 10.10.10.205
