# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:uRFeVFoC3ZM=,iv:brTxSSrLnssyP4T70yYjxBnaLg5qVsCY1G7jljY59hc=,tag:nGqi5uI+F5VyXvHmJPwtMQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:HDpC1V9EK/baxfUtrw==,iv:csVkDBXpR18dCL/1zv4jMy7qjZ6OjXxABjbXi0hzkaU=,tag:rrWEa/S8zHMMga66JD51jQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hwuafwcf6l05rd0erpl99wlrt5m644n5sxr5n0t70v93zj62humqh4j3ln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cFZUcWsvOXQ2OXNnUVNQ
            enVsYUZnWFFibFVOcmhyd3IrVjdyRGFBNVY4CnNzUi82WjFsbG00WnJZYUtRTzMx
            dVBJelFER2lhNHBoTklRbS9wY0dKSFkKLS0tIFJVa05DZGMyOGNxTFlVRGlhRHR2
            VW9KbG9iT256VlpZYVZhbEtHanVmWDQKiYGZgdmRaZ9wMDVdWuVIW9jUUnvOu4m1
            davgtOozVsgRGaisi6OHByRWSMFcFQEN4rl9gyM2mGCL+xrQDJGeoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-16T17:14:04Z"
    mac: ENC[AES256_GCM,data:NKYCpTCpP8ePR/J9Wkmwt7XHuE8S60Vr70HzSTh4hBuFnV0q+++BKZWuFAU/pLZUnAPl8r795Gb9jJu56e71dMtzKbmO9o17hRHXPlTAE9ZgxcOl6GLMFWXWcRsgn53wCq7QTtsjWd8XER0Ty2nKcuiGtkUkrew1MJTJbjX+6Tc=,iv:ssk+IzVXQIazyrzq/GL0Xf5XE2/SwMToNw9ye48kLZw=,tag:apbP6FSsNevOpbXbwGADmA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
